CREATE ROLE bookstore
LOGIN
SUPERUSER;
CREATE SCHEMA bookstore AUTHORIZATION bookstore

CREATE TABLE bookstore.BOOKS (
    ID INT NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    AUTHOR VARCHAR(50),
    PUBLISHER VARCHAR(50),
    GENRE VARCHAR(50),
    NUMBER_OF_PAGES NUMERIC,
    WEIGHT NUMERIC,
    PRICE DECIMAL,
    BOOK_TYPE VARCHAR(9),
    TITLE VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE bookstore.REVIEWS (
    ID INT NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    STAR_RATING DECIMAL NOT NULL,
    REVIEW_DESCRIPTION VARCHAR(295),
    PRIMARY KEY (ID)
);
commit;